apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "poc.name" . }}-backend
  labels:
    {{- include "poc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.image.backend }}
        ports:
        - containerPort: {{ .Values.service.backendPort }}
        resources:
          requests:
            memory: {{ .Values.resources.backend.requests.memory }}
            cpu: {{ .Values.resources.backend.requests.cpu }}
          limits:
            memory: {{ .Values.resources.backend.limits.memory }}
            cpu: {{ .Values.resources.backend.limits.cpu }}
        env:
        - name: MYSQL_HOST
          value: {{ include "poc.name" . }}-database
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: dbName
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: dbUser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: dbPassword
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.service.backendPort }}
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.service.backendPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3