apiVersion: v1
kind: Service
metadata:
  name: {{ include "poc.name" . }}-backend
  labels:
    {{- include "poc.labels" . | nindent 4 }}
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: {{ .Values.service.backendPort }}
    targetPort: {{ .Values.service.backendPort }}
  type: ClusterIP
