apiVersion: v1
kind: Service
metadata:
  name: {{ include "poc.name" . }}-database
  labels:
    {{- include "poc.labels" . | nindent 4 }}
spec:
  selector:
    app: database
  ports:
  - protocol: TCP
    port: {{ .Values.service.dbPort }}
    targetPort: {{ .Values.service.dbPort }}
  type: ClusterIP
