apiVersion: v1
kind: Service
metadata:
  name: {{ include "poc.name" . }}-frontend
  labels:
    {{- include "poc.labels" . | nindent 4 }}
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80
  type: {{ .Values.service.type }}
