apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  dbName: {{ .Values.secrets.dbName }}
  dbRootPassword: {{ .Values.secrets.dbRootPassword }}
  dbUser: {{ .Values.secrets.dbUser }}
  dbPassword: {{ .Values.secrets.dbPassword }}
